# Generated by Django 4.2.19 on 2025-02-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/dash.jpg', null=True, upload_to='media'),
        ),
    ]
